# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

  jobs:
    - install:
        # Install dependencies from requirements.txt
        - requirements: docs/requirements.txt
    - build:
        # Run your custom scripts before building the documentation
        - command: |
            python docs/generate_sp_docs.py
            python docs/generate_main_docs.py
            sphinx-build -b html docs/source docs/build/html
